### ISSUE TITLE
Assertion !err failed (likely due to font?) 

### ISSUE THREAD

**Issue by HerbFargus** [lilbud/es-theme-material#2]
I'll see if I can find out what it is, feel free to get on the #retropie IRC channel if you want to discuss things a little quicker

**Comment by lilbud** [comment]
How do you use IRC?

**Comment by HerbFargus** [comment]
they have online clients, I prefer to use a desktop client called hexchat. you just connect to freenode as the main server and #retropie as the channel. there are a bunch of guides online on how to use IRC

**Comment by lilbud** [comment]
I am connected right now

**Comment by HerbFargus** [comment]
well we determined it was the retropie svg.
